# Generated by Django 5.1.6 on 2025-02-25 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryApp', '0005_stock_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='received_quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
