# Generated by Django 5.1.6 on 2025-02-28 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryApp', '0006_stock_received_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockHistrory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('received_by', models.CharField(blank=True, max_length=50, null=True)),
                ('received_quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('issue_quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('issue_by', models.CharField(blank=True, max_length=50, null=True)),
                ('issue_to', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number', models.IntegerField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('reorder_level', models.IntegerField(blank=True, default=0, null=True)),
                ('last_update', models.DateTimeField(null=True)),
                ('timestamp', models.DateField(null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventoryApp.category')),
            ],
        ),
    ]
